image: "node:erbium-alpine"

stages:
  - test # Run unit tests
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

lint:
  stage: test
  before_script:
    - echo "//npm.knotcity.io/:_authToken=$NPM_TOKEN" >> .npmrc
    - npm ci
  script:
    - npm run lint

build:
  stage: build
  before_script:
    - echo "//npm.knotcity.io/:_authToken=$NPM_TOKEN" >> .npmrc
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - echo "//npm.knotcity.io/:_authToken=$NPM_TOKEN" >> .npmrc
  script:
    - npm publish
